# Generated by Django 3.2.8 on 2021-11-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tracks',
            field=models.ManyToManyField(to='iti.Track'),
        ),
    ]
