# Generated by Django 3.2.8 on 2021-11-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iti', '0002_course_tracks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tracks',
        ),
        migrations.AddField(
            model_name='track',
            name='courses',
            field=models.ManyToManyField(to='iti.Course'),
        ),
    ]
